version: '2'
services:
  cookbook:
    image: bglowacki/cookbook:latest
    depends_on:
      - postgresql_development
      - postgresql_test
    links:
      - postgresql_development:postgresql_development
      - postgresql_test:postgresql_test
    command: dockerize -timeout 30s -wait tcp://postgresql_development:5432  -wait tcp://postgresql_test:5432 ./start_dev
    ports:
      - 3000:3000
      - 8080:8080
    volumes:
      - ${PWD}:/usr/app
    environment:
      DOCKER_ENV: "true"

  postgresql_development:
    image: postgres
    volumes_from:
      - postgresql_development_data
    depends_on:
      - postgresql_development_data
    environment:
      POSTGRES_PASSWORD: cookbook
      POSTGRES_DB: cookbook_development

  postgresql_test:
      image: postgres
      environment:
        POSTGRES_PASSWORD: cookbook
        POSTGRES_DB: cookbook_test

  postgresql_development_data:
    image: busybox
    volumes:
      - /var/lib/postgresql/data