development:
  adapter: postgresql
  encoding: unicode
  database: cookbook_development
  pool: 5
  username: bartekglowacki

test:
  adapter: postgresql
  encoding: unicode
  database: cookbook_test
  pool: 5
  username: bartekglowacki