development:
  adapter: postgresql
  encoding: unicode
  database: cookbook_development
  pool: 5
  username: postgres
  password: cookbook
  host: postgresql

test:
  adapter: postgresql
  encoding: unicode
  database: cookbook_test
  pool: 5
  username: postgres
  password: cookbook
  host: postgresql